"""add bubbles and swipe records

Revision ID: 2593eb20f5aa
Revises: 9305bdac1f2c
Create Date: 2026-06-07 12:41:15.895679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2593eb20f5aa'
down_revision: Union[str, Sequence[str], None] = '9305bdac1f2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bubbles',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('tagline', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('bubble_type', sa.Enum('FAMILY', 'FRIEND_GROUP', 'COLLEGE_GROUP', 'WORK_GROUP', 'COMPANY', 'SPORTS_GROUP', 'OTHER', name='bubble_type'), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('cover_image_url', sa.String(length=1024), nullable=True),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('is_admin_created', sa.Boolean(), nullable=False),
    sa.Column('visibility', sa.Enum('PUBLIC', 'PRIVATE', name='bubble_visibility'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bubbles_created_by'), 'bubbles', ['created_by'], unique=False)
    op.create_index('ix_bubbles_visibility', 'bubbles', ['visibility'], unique=False)
    op.create_table('bubble_join_requests',
    sa.Column('bubble_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='bubble_join_status'), nullable=False),
    sa.Column('approvals', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('rejections', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bubble_id'], ['bubbles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bubble_id', 'user_id', name='uq_bubble_join_requests_bubble_user')
    )
    op.create_index(op.f('ix_bubble_join_requests_bubble_id'), 'bubble_join_requests', ['bubble_id'], unique=False)
    op.create_index('ix_bubble_join_requests_status', 'bubble_join_requests', ['bubble_id', 'status'], unique=False)
    op.create_index(op.f('ix_bubble_join_requests_user_id'), 'bubble_join_requests', ['user_id'], unique=False)
    op.create_table('bubble_members',
    sa.Column('bubble_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MEMBER', name='bubble_member_role'), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('previous_rank', sa.Integer(), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bubble_id'], ['bubbles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bubble_id', 'user_id', name='uq_bubble_members_bubble_user')
    )
    op.create_index(op.f('ix_bubble_members_bubble_id'), 'bubble_members', ['bubble_id'], unique=False)
    op.create_index('ix_bubble_members_score', 'bubble_members', ['bubble_id', 'score'], unique=False)
    op.create_index(op.f('ix_bubble_members_user_id'), 'bubble_members', ['user_id'], unique=False)
    op.create_table('swipe_records',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('direction', sa.Enum('ALIGN', 'OPPOSE', name='swipe_direction'), nullable=False),
    sa.Column('delta', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'account_id', name='uq_swipe_records_user_account')
    )
    op.create_index(op.f('ix_swipe_records_account_id'), 'swipe_records', ['account_id'], unique=False)
    op.create_index('ix_swipe_records_user_created', 'swipe_records', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_swipe_records_user_id'), 'swipe_records', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_swipe_records_user_id'), table_name='swipe_records')
    op.drop_index('ix_swipe_records_user_created', table_name='swipe_records')
    op.drop_index(op.f('ix_swipe_records_account_id'), table_name='swipe_records')
    op.drop_table('swipe_records')
    op.drop_index(op.f('ix_bubble_members_user_id'), table_name='bubble_members')
    op.drop_index('ix_bubble_members_score', table_name='bubble_members')
    op.drop_index(op.f('ix_bubble_members_bubble_id'), table_name='bubble_members')
    op.drop_table('bubble_members')
    op.drop_index(op.f('ix_bubble_join_requests_user_id'), table_name='bubble_join_requests')
    op.drop_index('ix_bubble_join_requests_status', table_name='bubble_join_requests')
    op.drop_index(op.f('ix_bubble_join_requests_bubble_id'), table_name='bubble_join_requests')
    op.drop_table('bubble_join_requests')
    op.drop_index('ix_bubbles_visibility', table_name='bubbles')
    op.drop_index(op.f('ix_bubbles_created_by'), table_name='bubbles')
    op.drop_table('bubbles')
    # ### end Alembic commands ###
