"""add scoring engine tables

Revision ID: 9305bdac1f2c
Revises: af39d0a34263
Create Date: 2026-06-05 12:57:29.198592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9305bdac1f2c'
down_revision: Union[str, Sequence[str], None] = 'af39d0a34263'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ledger_entries',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=True),
    sa.Column('delta', sa.Float(), nullable=False),
    sa.Column('base_score', sa.Float(), nullable=False),
    sa.Column('multiplier_quotient', sa.Float(), nullable=False),
    sa.Column('multipliers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('formula_version', sa.String(length=32), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('deed', sa.String(length=256), nullable=True),
    sa.Column('capped', sa.Boolean(), nullable=False),
    sa.Column('cause', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ledger_entries_account_id_timestamp', 'ledger_entries', ['account_id', 'timestamp'], unique=False)
    op.create_index('ix_ledger_entries_report_id', 'ledger_entries', ['report_id'], unique=False)
    op.add_column('accounts', sa.Column('score', sa.Float(), nullable=False, server_default='1000.0'))
    op.add_column('accounts', sa.Column('score_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('reports', sa.Column('deed', sa.String(length=256), nullable=True))
    op.add_column('reports', sa.Column('base_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'base_score')
    op.drop_column('reports', 'deed')
    op.drop_column('accounts', 'score_breakdown')
    op.drop_column('accounts', 'score')
    op.drop_index('ix_ledger_entries_report_id', table_name='ledger_entries')
    op.drop_index('ix_ledger_entries_account_id_timestamp', table_name='ledger_entries')
    op.drop_table('ledger_entries')
    # ### end Alembic commands ###
