"""add report type and evidence fields

Revision ID: af39d0a34263
Revises: ded40aceceda
Create Date: 2026-06-04 13:17:43.494837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'af39d0a34263'
down_revision: Union[str, Sequence[str], None] = 'ded40aceceda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('report_type', sa.String(length=16), nullable=True))
    op.add_column(
        'reports',
        sa.Column('is_irl', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    )
    op.alter_column('reports', 'is_irl', server_default=None)
    op.add_column('reports', sa.Column('evidence_source_url', sa.String(length=1024), nullable=True))
    op.add_column('reports', sa.Column('ai_verdict', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'ai_verdict')
    op.drop_column('reports', 'evidence_source_url')
    op.drop_column('reports', 'is_irl')
    op.drop_column('reports', 'report_type')
    # ### end Alembic commands ###
