"""add_v1_parity_tables

Revision ID: da0be9eec00d
Revises: 2593eb20f5aa
Create Date: 2026-06-09 01:53:38.956514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da0be9eec00d'
down_revision: Union[str, Sequence[str], None] = '2593eb20f5aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_settings_key'), 'site_settings', ['key'], unique=True)
    op.create_table('deletion_requests',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('user_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('attachment_urls', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'COMPLETED', name='deletion_request_status'), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_deletion_requests_status_created', 'deletion_requests', ['status', 'created_at'], unique=False)
    op.create_index('ix_deletion_requests_user_id', 'deletion_requests', ['user_id'], unique=False)
    op.create_table('issue_reports',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('issue_type', sa.String(length=64), nullable=False),
    sa.Column('page', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('attachment_urls', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True),
    sa.Column('device', sa.String(length=128), nullable=True),
    sa.Column('browser', sa.String(length=128), nullable=True),
    sa.Column('severity', sa.String(length=32), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'DISMISSED', name='issue_report_status'), nullable=False),
    sa.Column('submitted_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_issue_reports_status_created', 'issue_reports', ['status', 'created_at'], unique=False)
    op.create_table('subscriptions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tier', sa.Enum('FREE', 'PRO', name='subscription_tier'), nullable=False),
    sa.Column('daily_reports_used', sa.Integer(), nullable=False),
    sa.Column('daily_reports_reset_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=True)
    op.create_table('audit_requests',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'REJECTED', name='audit_request_status'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_requests_account_id', 'audit_requests', ['account_id'], unique=False)
    op.create_index('ix_audit_requests_status_created', 'audit_requests', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_requests_user_id'), 'audit_requests', ['user_id'], unique=False)
    op.create_table('events',
    sa.Column('subject_account_id', sa.UUID(), nullable=False),
    sa.Column('reporter_user_id', sa.UUID(), nullable=True),
    sa.Column('anonymous_tag', sa.String(length=64), nullable=True),
    sa.Column('event_type', sa.String(length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('base_impact_key', sa.String(length=128), nullable=True),
    sa.Column('base_impact', sa.Float(), nullable=True),
    sa.Column('multipliers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('multiplier_quotient', sa.Float(), nullable=True),
    sa.Column('delta', sa.Float(), nullable=True),
    sa.Column('score_before', sa.Float(), nullable=True),
    sa.Column('score_after', sa.Float(), nullable=True),
    sa.Column('decay', sa.Float(), nullable=True),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('deed', sa.String(length=128), nullable=True),
    sa.Column('week_id', sa.String(length=32), nullable=True),
    sa.Column('formula_version', sa.String(length=32), nullable=True),
    sa.Column('proof_links', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True),
    # report_status already exists in the DB (initial schema); reuse it, do not re-create the type.
    sa.Column('status', postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', 'REMOVED', name='report_status', create_type=False), nullable=False),
    sa.Column('ai_verdict', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('admin_decision', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('\'{"aligns"\\:0,"opposes"\\:0,"comments"\\:0,"shares"\\:0}\'::jsonb'), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reporter_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_reporter_user_id', 'events', ['reporter_user_id'], unique=False)
    op.create_index('ix_events_status_created', 'events', ['status', 'created_at'], unique=False)
    op.create_index('ix_events_subject_account_id', 'events', ['subject_account_id'], unique=False)
    op.create_table('evidence_proposals',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('scoring_deed', sa.String(length=128), nullable=True),
    sa.Column('report_type', sa.String(length=16), nullable=True),
    sa.Column('scoring_category', sa.String(length=128), nullable=True),
    sa.Column('base_score', sa.Float(), nullable=True),
    sa.Column('suggested_impact', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source_urls', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True),
    sa.Column('source_titles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='evidence_proposal_status'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('report_id', sa.UUID(), nullable=True),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('reporter_user_id', sa.UUID(), nullable=True),
    sa.Column('created_by_admin_id', sa.UUID(), nullable=True),
    sa.Column('anonymous_tag', sa.String(length=64), nullable=True),
    sa.Column('public_anonymous', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reporter_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_evidence_proposals_account_id', 'evidence_proposals', ['account_id'], unique=False)
    op.create_index('ix_evidence_proposals_status_created', 'evidence_proposals', ['status', 'created_at'], unique=False)
    op.create_table('moderation_requests',
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('evidence_links', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='moderation_request_status'), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_moderation_requests_report_id', 'moderation_requests', ['report_id'], unique=False)
    op.create_index('ix_moderation_requests_status_created', 'moderation_requests', ['status', 'created_at'], unique=False)
    op.create_table('report_bookmarks',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'report_id', name='uq_report_bookmarks_user_report')
    )
    op.create_index(op.f('ix_report_bookmarks_report_id'), 'report_bookmarks', ['report_id'], unique=False)
    op.create_index(op.f('ix_report_bookmarks_user_id'), 'report_bookmarks', ['user_id'], unique=False)
    op.create_table('report_metadata',
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('multipliers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('labels', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('admin_overrides', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('multiplier_quotient', sa.Float(), nullable=True),
    sa.Column('formula_version', sa.String(length=32), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_metadata_report_id'), 'report_metadata', ['report_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_metadata_report_id'), table_name='report_metadata')
    op.drop_table('report_metadata')
    op.drop_index(op.f('ix_report_bookmarks_user_id'), table_name='report_bookmarks')
    op.drop_index(op.f('ix_report_bookmarks_report_id'), table_name='report_bookmarks')
    op.drop_table('report_bookmarks')
    op.drop_index('ix_moderation_requests_status_created', table_name='moderation_requests')
    op.drop_index('ix_moderation_requests_report_id', table_name='moderation_requests')
    op.drop_table('moderation_requests')
    op.drop_index('ix_evidence_proposals_status_created', table_name='evidence_proposals')
    op.drop_index('ix_evidence_proposals_account_id', table_name='evidence_proposals')
    op.drop_table('evidence_proposals')
    op.drop_index('ix_events_subject_account_id', table_name='events')
    op.drop_index('ix_events_status_created', table_name='events')
    op.drop_index('ix_events_reporter_user_id', table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_audit_requests_user_id'), table_name='audit_requests')
    op.drop_index('ix_audit_requests_status_created', table_name='audit_requests')
    op.drop_index('ix_audit_requests_account_id', table_name='audit_requests')
    op.drop_table('audit_requests')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index('ix_issue_reports_status_created', table_name='issue_reports')
    op.drop_table('issue_reports')
    op.drop_index('ix_deletion_requests_user_id', table_name='deletion_requests')
    op.drop_index('ix_deletion_requests_status_created', table_name='deletion_requests')
    op.drop_table('deletion_requests')
    op.drop_index(op.f('ix_site_settings_key'), table_name='site_settings')
    op.drop_table('site_settings')
    # ### end Alembic commands ###

    # Drop enum types created by this migration (report_status is shared and preserved).
    op.execute('DROP TYPE IF EXISTS subscription_tier')
    op.execute('DROP TYPE IF EXISTS issue_report_status')
    op.execute('DROP TYPE IF EXISTS deletion_request_status')
    op.execute('DROP TYPE IF EXISTS audit_request_status')
    op.execute('DROP TYPE IF EXISTS evidence_proposal_status')
    op.execute('DROP TYPE IF EXISTS moderation_request_status')
