"""initial schema

Revision ID: ded40aceceda
Revises: 
Create Date: 2026-06-03 14:36:03.154488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ded40aceceda'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('firebase_uid', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('photo_url', sa.String(length=1024), nullable=True),
    sa.Column('role', sa.Enum('USER', 'MODERATOR', 'ADMIN', 'SUPER_ADMIN', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('firebase_uid'),
    sa.UniqueConstraint('username')
    )
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_table('accounts',
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('handle', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=True),
    sa.Column('bio', sa.String(length=2000), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'UNDER_REVIEW', 'DISPUTED', 'REMOVED', name='account_status'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'handle', name='uq_accounts_platform_handle')
    )
    op.create_index(op.f('ix_accounts_owner_user_id'), 'accounts', ['owner_user_id'], unique=False)
    op.create_index('ix_accounts_status', 'accounts', ['status'], unique=False)
    op.create_table('admin_actions',
    sa.Column('actor_user_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.Enum('REPORT_REVIEW', 'CLAIM_REVIEW', 'DISPUTE_REVIEW', 'ACCOUNT_MODERATION', 'USER_ROLE_UPDATE', name='admin_action_type'), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_admin_actions_actor_created', 'admin_actions', ['actor_user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_admin_actions_actor_user_id'), 'admin_actions', ['actor_user_id'], unique=False)
    op.create_index('ix_admin_actions_target', 'admin_actions', ['target_type', 'target_id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('notification_type', sa.Enum('CLAIM', 'REPORT', 'DISPUTE', 'TRUST_BADGE', 'MODERATION', 'SYSTEM', name='notification_type'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.String(length=2000), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_user_read_created', 'notifications', ['user_id', 'is_read', 'created_at'], unique=False)
    op.create_table('account_social_links',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'platform', name='uq_account_social_links_account_platform')
    )
    op.create_index(op.f('ix_account_social_links_account_id'), 'account_social_links', ['account_id'], unique=False)
    op.create_table('claim_requests',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('requester_user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='claim_request_status'), nullable=False),
    sa.Column('evidence_type', sa.String(length=64), nullable=True),
    sa.Column('evidence_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requester_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'requester_user_id', name='uq_claim_requests_account_requester')
    )
    op.create_index(op.f('ix_claim_requests_account_id'), 'claim_requests', ['account_id'], unique=False)
    op.create_index(op.f('ix_claim_requests_requester_user_id'), 'claim_requests', ['requester_user_id'], unique=False)
    op.create_index(op.f('ix_claim_requests_reviewed_by'), 'claim_requests', ['reviewed_by'], unique=False)
    op.create_index('ix_claim_requests_status_created', 'claim_requests', ['status', 'created_at'], unique=False)
    op.create_table('reports',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('reporter_user_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'REMOVED', name='report_status'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reporter_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reports_account_created', 'reports', ['account_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_reports_account_id'), 'reports', ['account_id'], unique=False)
    op.create_index(op.f('ix_reports_reporter_user_id'), 'reports', ['reporter_user_id'], unique=False)
    op.create_index(op.f('ix_reports_reviewed_by'), 'reports', ['reviewed_by'], unique=False)
    op.create_index('ix_reports_reviewer_reviewed_at', 'reports', ['reviewed_by', 'reviewed_at'], unique=False)
    op.create_index('ix_reports_status_created', 'reports', ['status', 'created_at'], unique=False)
    op.create_table('disputes',
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('requester_user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'UNDER_REVIEW', 'ACCEPTED', 'REJECTED', 'WITHDRAWN', name='dispute_status'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('evidence_url', sa.String(length=1024), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requester_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disputes_account_id'), 'disputes', ['account_id'], unique=False)
    op.create_index(op.f('ix_disputes_report_id'), 'disputes', ['report_id'], unique=False)
    op.create_index(op.f('ix_disputes_requester_user_id'), 'disputes', ['requester_user_id'], unique=False)
    op.create_index(op.f('ix_disputes_reviewed_by'), 'disputes', ['reviewed_by'], unique=False)
    op.create_index('ix_disputes_status_created', 'disputes', ['status', 'created_at'], unique=False)
    op.create_table('report_comments',
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_comments_report_id'), 'report_comments', ['report_id'], unique=False)
    op.create_index(op.f('ix_report_comments_user_id'), 'report_comments', ['user_id'], unique=False)
    op.create_table('report_media',
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('media_type', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_media_report_id'), 'report_media', ['report_id'], unique=False)
    op.create_table('report_votes',
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('vote_type', sa.Enum('ALIGN', 'OPPOSE', name='vote_type'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id', 'user_id', name='uq_report_votes_report_user')
    )
    op.create_index(op.f('ix_report_votes_report_id'), 'report_votes', ['report_id'], unique=False)
    op.create_index(op.f('ix_report_votes_user_id'), 'report_votes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_votes_user_id'), table_name='report_votes')
    op.drop_index(op.f('ix_report_votes_report_id'), table_name='report_votes')
    op.drop_table('report_votes')
    op.drop_index(op.f('ix_report_media_report_id'), table_name='report_media')
    op.drop_table('report_media')
    op.drop_index(op.f('ix_report_comments_user_id'), table_name='report_comments')
    op.drop_index(op.f('ix_report_comments_report_id'), table_name='report_comments')
    op.drop_table('report_comments')
    op.drop_index('ix_disputes_status_created', table_name='disputes')
    op.drop_index(op.f('ix_disputes_reviewed_by'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_requester_user_id'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_report_id'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_account_id'), table_name='disputes')
    op.drop_table('disputes')
    op.drop_index('ix_reports_status_created', table_name='reports')
    op.drop_index('ix_reports_reviewer_reviewed_at', table_name='reports')
    op.drop_index(op.f('ix_reports_reviewed_by'), table_name='reports')
    op.drop_index(op.f('ix_reports_reporter_user_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_account_id'), table_name='reports')
    op.drop_index('ix_reports_account_created', table_name='reports')
    op.drop_table('reports')
    op.drop_index('ix_claim_requests_status_created', table_name='claim_requests')
    op.drop_index(op.f('ix_claim_requests_reviewed_by'), table_name='claim_requests')
    op.drop_index(op.f('ix_claim_requests_requester_user_id'), table_name='claim_requests')
    op.drop_index(op.f('ix_claim_requests_account_id'), table_name='claim_requests')
    op.drop_table('claim_requests')
    op.drop_index(op.f('ix_account_social_links_account_id'), table_name='account_social_links')
    op.drop_table('account_social_links')
    op.drop_index('ix_notifications_user_read_created', table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_admin_actions_target', table_name='admin_actions')
    op.drop_index(op.f('ix_admin_actions_actor_user_id'), table_name='admin_actions')
    op.drop_index('ix_admin_actions_actor_created', table_name='admin_actions')
    op.drop_table('admin_actions')
    op.drop_index('ix_accounts_status', table_name='accounts')
    op.drop_index(op.f('ix_accounts_owner_user_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
