export type SheetImpactType = 'positive' | 'negative';

export type SheetScoringIndexRow = {
  category: string;
  deed: string;
  type: SheetImpactType;
  baseScore: number;
};

export const CIRCUMSTANCES_LABELS: Record<string, string> = {
  '0.5': 'Extreme Pressure',
  '1': 'Normal',
  '1.5': 'Manageable',
  '2': 'Favorable',
  '2.5': 'Highly Favorable',
  '3': 'Optimal',
};

export const SHEET_SCORING_INDEX: SheetScoringIndexRow[] = [
  { category: 'Micro | Everyday Actions', deed: 'Cleaning shared spaces', type: 'positive', baseScore: 20 },
  { category: 'Micro | Everyday Actions', deed: 'Returning lost items', type: 'positive', baseScore: 20 },
  { category: 'Micro | Everyday Actions', deed: 'Holding doors / basic courtesy', type: 'positive', baseScore: 10 },
  { category: 'Micro | Everyday Actions', deed: 'Helping someone with small tasks', type: 'positive', baseScore: 30 },
  { category: 'Micro | Everyday Actions', deed: 'Giving directions / assistance', type: 'positive', baseScore: 20 },
  { category: 'Micro | Everyday Actions', deed: 'Littering', type: 'negative', baseScore: -10 },
  { category: 'Micro | Everyday Actions', deed: 'Being rude / insulting', type: 'negative', baseScore: -20 },
  { category: 'Micro | Everyday Actions', deed: 'Cutting queues', type: 'negative', baseScore: -30 },
  { category: 'Micro | Everyday Actions', deed: 'Ignoring basic courtesy', type: 'negative', baseScore: -10 },
  { category: 'Micro | Everyday Actions', deed: 'Minor harassment (offline/online)', type: 'negative', baseScore: -30 },
  { category: 'Social | Interpersonal', deed: 'Supporting a friend emotionally', type: 'positive', baseScore: 50 },
  { category: 'Social | Interpersonal', deed: 'Resolving conflict peacefully', type: 'positive', baseScore: 70 },
  { category: 'Social | Interpersonal', deed: 'Standing up for someone', type: 'positive', baseScore: 100 },
  { category: 'Social | Interpersonal', deed: 'Mentoring / guiding', type: 'positive', baseScore: 70 },
  { category: 'Social | Interpersonal', deed: 'Public kindness to strangers', type: 'positive', baseScore: 50 },
  { category: 'Social | Interpersonal', deed: 'Bullying (offline/online)', type: 'negative', baseScore: -70 },
  { category: 'Social | Interpersonal', deed: 'Public humiliation', type: 'negative', baseScore: -100 },
  { category: 'Social | Interpersonal', deed: 'Gaslighting / manipulation', type: 'negative', baseScore: -50 },
  { category: 'Social | Interpersonal', deed: 'Harassment / stalking', type: 'negative', baseScore: -100 },
  { category: 'Social | Interpersonal', deed: 'Spreading rumors', type: 'negative', baseScore: -70 },
  { category: 'Online Behavior', deed: 'Sharing helpful information', type: 'positive', baseScore: 50 },
  { category: 'Online Behavior', deed: 'Educating / awareness content', type: 'positive', baseScore: 50 },
  { category: 'Online Behavior', deed: 'Amplifying good causes', type: 'positive', baseScore: 80 },
  { category: 'Online Behavior', deed: 'Calling out injustice responsibly', type: 'positive', baseScore: 120 },
  { category: 'Online Behavior', deed: 'Hate comments', type: 'negative', baseScore: -50 },
  { category: 'Online Behavior', deed: 'Trolling', type: 'negative', baseScore: -80 },
  { category: 'Online Behavior', deed: 'Doxxing', type: 'negative', baseScore: -120 },
  { category: 'Online Behavior', deed: 'Spreading misinformation', type: 'negative', baseScore: -50 },
  { category: 'Online Behavior', deed: 'Cancel mob participation', type: 'negative', baseScore: -80 },
  { category: 'Online Behavior', deed: 'Impersonation', type: 'negative', baseScore: -120 },
  { category: 'Financial | Transactional', deed: 'Lending money', type: 'positive', baseScore: 100 },
  { category: 'Financial | Transactional', deed: 'Donating', type: 'positive', baseScore: 200 },
  { category: 'Financial | Transactional', deed: 'Paying fairly', type: 'positive', baseScore: 100 },
  { category: 'Financial | Transactional', deed: 'Supporting small businesses', type: 'positive', baseScore: 200 },
  { category: 'Financial | Transactional', deed: 'Funding education / causes', type: 'positive', baseScore: 300 },
  { category: 'Financial | Transactional', deed: 'Scamming / fraud', type: 'negative', baseScore: -200 },
  { category: 'Financial | Transactional', deed: 'Not repaying loans', type: 'negative', baseScore: -100 },
  { category: 'Financial | Transactional', deed: 'Exploiting workers', type: 'negative', baseScore: -300 },
  { category: 'Financial | Transactional', deed: 'Bribery', type: 'negative', baseScore: -300 },
  { category: 'Financial | Transactional', deed: 'Tax evasion', type: 'negative', baseScore: -200 },
  { category: 'Financial | Transactional', deed: 'Financial manipulation', type: 'negative', baseScore: -100 },
  { category: 'Professional | Power Use', deed: 'Creating jobs', type: 'positive', baseScore: 600 },
  { category: 'Professional | Power Use', deed: 'Ethical leadership', type: 'positive', baseScore: 400 },
  { category: 'Professional | Power Use', deed: 'Fair hiring', type: 'positive', baseScore: 200 },
  { category: 'Professional | Power Use', deed: 'Whistleblowing', type: 'positive', baseScore: 600 },
  { category: 'Professional | Power Use', deed: 'Building useful products', type: 'positive', baseScore: 400 },
  { category: 'Professional | Power Use', deed: 'Abuse of power', type: 'negative', baseScore: -400 },
  { category: 'Professional | Power Use', deed: 'Workplace harassment', type: 'negative', baseScore: -600 },
  { category: 'Professional | Power Use', deed: 'Discrimination', type: 'negative', baseScore: -400 },
  { category: 'Professional | Power Use', deed: 'Corruption', type: 'negative', baseScore: -400 },
  { category: 'Professional | Power Use', deed: 'Exploitation', type: 'negative', baseScore: -200 },
  { category: 'Professional | Power Use', deed: 'Unethical decisions affecting others', type: 'negative', baseScore: -200 },
  { category: 'Community | Public Impact', deed: 'Volunteering', type: 'positive', baseScore: 150 },
  { category: 'Community | Public Impact', deed: 'Organizing community help', type: 'positive', baseScore: 300 },
  { category: 'Community | Public Impact', deed: 'Environmental action (cleanup, planting)', type: 'positive', baseScore: 500 },
  { category: 'Community | Public Impact', deed: 'Disaster relief participation', type: 'positive', baseScore: 300 },
  { category: 'Community | Public Impact', deed: 'Public nuisance', type: 'negative', baseScore: -150 },
  { category: 'Community | Public Impact', deed: 'Vandalism', type: 'negative', baseScore: -300 },
  { category: 'Community | Public Impact', deed: 'Environmental damage', type: 'negative', baseScore: -300 },
  { category: 'Community | Public Impact', deed: 'Inciting unrest', type: 'negative', baseScore: -500 },
  { category: 'Community | Public Impact', deed: 'Destroying public property', type: 'negative', baseScore: -300 },
  { category: 'Health | Safety', deed: 'Helping injured people', type: 'positive', baseScore: 300 },
  { category: 'Health | Safety', deed: 'Donating blood/organs', type: 'positive', baseScore: 600 },
  { category: 'Health | Safety', deed: 'Saving someone in danger', type: 'positive', baseScore: 900 },
  { category: 'Health | Safety', deed: 'Promoting safety', type: 'positive', baseScore: 300 },
  { category: 'Health | Safety', deed: 'Drunk driving', type: 'negative', baseScore: -600 },
  { category: 'Health | Safety', deed: 'Negligence causing harm', type: 'negative', baseScore: -300 },
  { category: 'Health | Safety', deed: 'Endangering others', type: 'negative', baseScore: -900 },
  { category: 'Health | Safety', deed: 'Ignoring safety protocols', type: 'negative', baseScore: -300 },
  { category: 'Legal | Criminal', deed: 'Reporting crime responsibly', type: 'positive', baseScore: 200 },
  { category: 'Legal | Criminal', deed: 'Cooperating with law enforcement', type: 'positive', baseScore: 300 },
  { category: 'Legal | Criminal', deed: 'Legal advocacy', type: 'positive', baseScore: 200 },
  { category: 'Legal | Criminal', deed: 'Theft', type: 'negative', baseScore: -300 },
  { category: 'Legal | Criminal', deed: 'Assault', type: 'negative', baseScore: -500 },
  { category: 'Legal | Criminal', deed: 'Kidnapping', type: 'negative', baseScore: -700 },
  { category: 'Legal | Criminal', deed: 'Sexual assault', type: 'negative', baseScore: -900 },
  { category: 'Legal | Criminal', deed: 'Murder', type: 'negative', baseScore: -1000 },
  { category: 'Legal | Criminal', deed: 'Organized crime', type: 'negative', baseScore: -1000 },
  { category: 'Large Scale | Systemic', deed: 'Policy improving lives', type: 'positive', baseScore: 500 },
  { category: 'Large Scale | Systemic', deed: 'Large-scale philanthropy', type: 'positive', baseScore: 800 },
  { category: 'Large Scale | Systemic', deed: 'Infrastructure development', type: 'positive', baseScore: 500 },
  { category: 'Large Scale | Systemic', deed: 'Conflict resolution', type: 'positive', baseScore: 800 },
  { category: 'Large Scale | Systemic', deed: 'War crimes', type: 'negative', baseScore: -1000 },
  { category: 'Large Scale | Systemic', deed: 'Genocide', type: 'negative', baseScore: -1000 },
  { category: 'Large Scale | Systemic', deed: 'Mass corruption', type: 'negative', baseScore: -1000 },
  { category: 'Large Scale | Systemic', deed: 'Large-scale exploitation', type: 'negative', baseScore: -1000 },
  { category: 'Large Scale | Systemic', deed: 'Economic harm affecting populations', type: 'negative', baseScore: -800 },
  { category: 'Extreme Impact', deed: 'Saving a life', type: 'positive', baseScore: 1000 },
  { category: 'Extreme Impact', deed: 'Saving multiple lives', type: 'positive', baseScore: 1500 },
  { category: 'Extreme Impact', deed: 'Large rescue', type: 'positive', baseScore: 2500 },
  { category: 'Extreme Impact', deed: 'Mass rescue / disaster intervention', type: 'positive', baseScore: 3500 },
  { category: 'Extreme Impact', deed: 'City-scale life impact / relief', type: 'positive', baseScore: 5000 },
  { category: 'Extreme Impact', deed: 'Nation-scale humanitarian action', type: 'positive', baseScore: 8000 },
  { category: 'Extreme Impact', deed: 'Global / historic life-saving impact', type: 'positive', baseScore: 10000 },
  { category: 'Extreme Impact', deed: 'Murder / rape', type: 'negative', baseScore: -1000 },
  { category: 'Extreme Impact', deed: 'Multiple victims', type: 'negative', baseScore: -1500 },
  { category: 'Extreme Impact', deed: 'Mass violence incident', type: 'negative', baseScore: -2500 },
  { category: 'Extreme Impact', deed: 'Large-scale violent event / riot causing deaths', type: 'negative', baseScore: -3500 },
  { category: 'Extreme Impact', deed: 'City-scale harm / coordinated violence', type: 'negative', baseScore: -5000 },
  { category: 'Extreme Impact', deed: 'Nation-scale harm / war-level impact', type: 'negative', baseScore: -8000 },
  { category: 'Extreme Impact', deed: 'Genocide / war crimes / systemic mass killing', type: 'negative', baseScore: -10000 },
];
